# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-17 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
